# Generated by Django 4.2.5 on 2023-12-24 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Light",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("ip", models.CharField(max_length=100)),
                ("is_on", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "creation_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            12,
                            24,
                            15,
                            12,
                            17,
                            868261,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "last_communication_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            12,
                            24,
                            15,
                            12,
                            17,
                            868295,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Light2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("ip", models.CharField(max_length=100)),
                ("is_on", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "creation_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            12,
                            24,
                            15,
                            12,
                            17,
                            868868,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "last_communication_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            12,
                            24,
                            15,
                            12,
                            17,
                            868887,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
        ),
    ]
