# Generated by Django 4.2.5 on 2023-12-24 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lights", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Light2",
        ),
        migrations.AlterField(
            model_name="light",
            name="creation_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 24, 15, 12, 26, 877617, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="light",
            name="last_communication_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 24, 15, 12, 26, 877652, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
